FROM centos:7

ARG WORK_DIR

ARG SIGNALWIRE_USER
ARG SIGNALWIRE_PASSWORD

ARG VERSION
ARG RELEASE
ARG FS_USER
ARG FS_GROUP
ARG MOD_DIR

ARG FREESWITCH_DEVEL_VERSION

ENV RPMBUILD=${WORK_DIR}/rpmbuild

WORKDIR ${WORK_DIR}

## fix to solve Centos 7 end-of-support
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update && yum clean all && yum -y install \
    createrepo \
    epel-release \
    rpm-build \
    rpmdevtools \
    rpmlint \
    yum-config-manager \
    wget \
    git \
    gcc \
    pkgconfig

RUN echo "$SIGNALWIRE_USER" > /etc/yum/vars/signalwireusername && \
    echo "$SIGNALWIRE_PASSWORD" > /etc/yum/vars/signalwiretoken && \
    yum install -y https://$(< /etc/yum/vars/signalwireusername):$(< /etc/yum/vars/signalwiretoken)@freeswitch.signalwire.com/repo/yum/centos-release/freeswitch-release-repo-0-1.noarch.rpm && \
    yum clean all && yum repolist

RUN yum -y install freeswitch-devel-${FREESWITCH_DEVEL_VERSION}

RUN rpmdev-setuptree && \
    mkdir -p ${WORK_DIR}/rpmbuild/BUILD/mod_free_amd

COPY Makefile mod_free_amd.c ${WORK_DIR}/rpmbuild/BUILD/mod_free_amd/

COPY RPM/freeswitch-mod-free-amd.spec ${WORK_DIR}/rpmbuild/SPECS/

RUN ls -la ${WORK_DIR}/rpmbuild/

RUN tar -zcvf ${WORK_DIR}/rpmbuild/SOURCES/freeswitch-mod-free-amd.tar.gz -C ${WORK_DIR}/rpmbuild/BUILD mod_free_amd

CMD ["bash","-c", "rpmbuild -vv -bb --define 'fs_version $VERSION' --define 'fs_release $RELEASE' --define 'fs_user $FS_USER' --define 'fs_group $FS_GROUP' --define 'mod_dir $MOD_DIR' $WORK_DIR/rpmbuild/SPECS/freeswitch-mod-free-amd.spec"]
